name: Opus — Build on MacOS

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (MacOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GNU autotools
        run: |
          brew update
          brew install autoconf automake libtool m4 pkg-config

      - name: Configure CMake
        run: |
          ./configure CC="gcc -arch x86_64 -arch arm64" --enable-deep-plc

      - name: Build
        run: |
          make
          make check

      - name: Move libopus.a
        run: |
          mv -v .libs/libopus.a libopus.a

      - name: Upload libopus.a and headers
        uses: actions/upload-artifact@v4
        with:
          name: opus-${{ runner.os }}
          path: |
            libopus.a
            include/opus_custom.h
            include/opus_defines.h
            include/opus_multistream.h
            include/opus_projection.h
            include/opus_types.h
            include/opus.h
