name: Opus — Build on Windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Cmake
        run: cmake -S . -B build -DBUILD_SHARED_LIBS=OFF -DOPUS_ENABLE_DEEP_PLC=ON

      - name: Build Standalone
        run: cmake --build build --config Release

      - name: Find
        shell: bash
        run: |
          pwd
          find . -type f

      - name: Upload libopus.a and headers
        uses: actions/upload-artifact@v4
        with:
          name: opus-${{ runner.os }}
          path: |
            build/Release/opus.lib
            include/opus_custom.h
            include/opus_defines.h
            include/opus_multistream.h
            include/opus_projection.h
            include/opus_types.h
            include/opus.h
